<script setup lang="ts">
definePageMeta({
  layout: 'default',
})

useHead({
  title: 'Terms of Service — GoGoSpace',
})
</script>

<template>
  <section class="section-padding pt-24 sm:pt-28">
    <div class="mx-auto max-w-3xl px-4 sm:px-6">
      <header class="border-b border-border pb-8 sm:pb-10">
        <h1 class="font-display text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl">
          Terms of Service
        </h1>
        <p class="mt-3 text-base text-muted-foreground sm:mt-4 sm:text-lg">
          Last updated: August 28, 2026
        </p>
      </header>

      <div class="legal-content mt-10 space-y-10 sm:mt-12 sm:space-y-12">
        <section>
          <h2>1. Agreement to Terms</h2>
          <p>
            These Terms of Service ("Terms") govern your access to and use of the GoGoSpace website,
            applications, and related services (collectively, the "Service") operated by GoGoSpace
            ("we," "us," or "our"). By accessing or using the Service, you agree to be bound by
            these Terms. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            GoGoSpace is an AI-powered interior design tool that allows you to upload photos of
            interior spaces or sketches and generate visual design concepts. The Service is intended
            for inspiration, ideation, and visualization purposes. AI-generated results are
            illustrative and do not constitute professional architectural, engineering, or interior
            design advice.
          </p>
        </section>

        <section>
          <h2>3. Eligibility and Accounts</h2>
          <p>
            You must be at least 18 years old, or the age of legal majority in your jurisdiction,
            to use the Service. When you create an account, you agree to provide accurate information
            and to keep your login credentials secure. You are responsible for all activity that
            occurs under your account.
          </p>
        </section>

        <section>
          <h2>4. Your Content</h2>
          <p>
            You may upload photos, sketches, and other materials ("User Content") to the Service.
            You retain ownership of your User Content. By uploading User Content, you grant us a
            limited, non-exclusive license to host, process, and display that content solely to
            provide and improve the Service for you — including generating design outputs based on
            your uploads.
          </p>
          <p>
            You represent that you have the right to upload your User Content and that it does not
            infringe any third party's intellectual property, privacy, or other rights. Do not upload
            content that is unlawful, harmful, or contains personal information of others without
            their consent.
          </p>
        </section>

        <section>
          <h2>5. AI-Generated Outputs</h2>
          <p>
            Designs and images produced by the Service ("Outputs") are generated by artificial
            intelligence based on your inputs and selected styles. Outputs may not be perfectly
            accurate, feasible, or suitable for construction or renovation without professional
            review.
          </p>
          <p>
            Subject to your compliance with these Terms and any applicable subscription plan, we
            grant you a personal, non-exclusive license to use Outputs for your own personal or
            commercial projects, including sharing them with contractors, clients, or collaborators.
            We do not claim ownership of Outputs generated specifically for you.
          </p>
        </section>

        <section>
          <h2>6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose or in violation of applicable laws</li>
            <li>Upload content that is obscene, defamatory, harassing, or otherwise objectionable</li>
            <li>Attempt to reverse engineer, scrape, or extract our models, algorithms, or source code</li>
            <li>Circumvent usage limits, access controls, or payment requirements</li>
            <li>Use automated means to access the Service without our prior written consent</li>
            <li>Misrepresent AI-generated Outputs as human-created professional design work where prohibited by law</li>
          </ul>
        </section>

        <section>
          <h2>7. Subscriptions and Payments</h2>
          <p>
            Certain features of the Service may require a paid subscription. Fees, billing cycles,
            and included usage are described at the time of purchase. Subscriptions renew automatically
            unless cancelled before the renewal date. Refunds are handled in accordance with our
            refund policy stated at checkout or as required by applicable law.
          </p>
          <p>
            We may change pricing or plan features with reasonable notice. Continued use after a
            price change takes effect constitutes acceptance of the new pricing for subsequent
            billing periods.
          </p>
        </section>

        <section>
          <h2>8. Intellectual Property</h2>
          <p>
            The Service, including its software, branding, design, and documentation (excluding your
            User Content and your licensed Outputs), is owned by GoGoSpace and protected by
            intellectual property laws. Nothing in these Terms grants you any right to use our
            trademarks, logos, or branding without prior written permission.
          </p>
        </section>

        <section>
          <h2>9. Privacy</h2>
          <p>
            Your use of the Service is also governed by our
            <NuxtLink to="/policy" class="text-primary hover:underline">Privacy Policy</NuxtLink>,
            which explains how we collect, use, and protect your information.
          </p>
        </section>

        <section>
          <h2>10. Disclaimers</h2>
          <p>
            THE SERVICE AND ALL OUTPUTS ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES
            OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE
            WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT OUTPUTS WILL MEET YOUR EXPECTATIONS OR BE
            SUITABLE FOR ANY SPECIFIC RENOVATION OR CONSTRUCTION PROJECT.
          </p>
        </section>

        <section>
          <h2>11. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, GOGOSPACE AND ITS OFFICERS, DIRECTORS, EMPLOYEES,
            AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
            OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF
            THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS OR THE SERVICE
            SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS BEFORE
            THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS (USD $100).
          </p>
        </section>

        <section>
          <h2>12. Termination</h2>
          <p>
            You may stop using the Service at any time. We may suspend or terminate your access if
            you violate these Terms, if required by law, or if we discontinue the Service. Upon
            termination, your right to use the Service ends, though provisions that by their nature
            should survive (including ownership, disclaimers, and limitations of liability) will
            remain in effect.
          </p>
        </section>

        <section>
          <h2>13. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. When we make material changes, we will
            post the updated Terms on this page and update the "Last updated" date. Your continued
            use of the Service after changes become effective constitutes acceptance of the revised
            Terms.
          </p>
        </section>

        <section>
          <h2>14. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the jurisdiction in which GoGoSpace operates,
            without regard to conflict-of-law principles. Any disputes shall be resolved in the
            courts of that jurisdiction, unless otherwise required by applicable consumer protection
            laws in your country of residence.
          </p>
        </section>

        <section>
          <h2>15. Contact</h2>
          <p>
            If you have questions about these Terms, please contact us at
            <a href="mailto:hello@gogospace.com" class="text-primary hover:underline">hello@gogospace.com</a>
            or visit our <NuxtLink to="/contact" class="text-primary hover:underline">Contact</NuxtLink> page.
          </p>
        </section>
      </div>
    </div>
  </section>
</template>

<style scoped>
.legal-content h2 {
  @apply text-xl font-semibold text-foreground sm:text-2xl;
}

.legal-content p {
  @apply mt-3 text-base leading-relaxed text-muted-foreground sm:mt-4 sm:text-lg;
}

.legal-content ul {
  @apply mt-3 list-disc space-y-2 pl-5 text-base text-muted-foreground sm:mt-4 sm:text-lg;
}
</style>
